[workspace]
resolver = "2"
members = ["assh", "assh-auth", "assh-channel"]

[workspace.package]
repository = "https://github.com/lowlevl/assh"
readme = "README.md"
license = "GPL-3.0"
keywords = ["ssh", "server", "client"]
authors = ["Maya the bee <15341887+lowlevl@users.noreply.github.com>"]
version = "0.0.0"
edition = "2021"

[workspace.dependencies]
assh = "^0"

async-trait = "0.1.73"
futures = "0.3.28"

[patch.crates-io]
assh = { path = "assh" }

