[package]
name = "assh"
description = "A low-level SSH library handling the transport and key-exchange, not more, not less."
documentation = "https://docs.rs/assh"
repository = "https://github.com/Nurrl/assh"
readme = "README.md"
license = "GPL-3.0"
keywords = ["ssh", "binary"]
authors = ["Maya the bee <15341887+Nurrl@users.noreply.github.com>"]
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]

# Whether to pass `--all-features` to Cargo (default: false)
all-features = true

# Enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
ssh-key = "0.6.1"
ssh-packet = "0.1.3"

thiserror = "1.0.49"
