[package]
name = "assh"
description = "A low-level SSH library handling the transport and key-exchange, not more, not less."
documentation = "https://docs.rs/assh"
repository = "https://github.com/Nurrl/assh"
readme = "README.md"
license = "GPL-3.0"
keywords = ["ssh", "binary"]
authors = ["Maya the bee <15341887+Nurrl@users.noreply.github.com>"]
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]

# Whether to pass `--all-features` to Cargo (default: false)
all-features = true

# Enable unstable features in the documentation
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
tracing = "0.1.37"
thiserror = "1.0.49"
futures = "0.3.28"
futures-time = "3.0.0"
strum = { version = "0.25.0", features = ["derive"] }
replace_with = "0.1.7"

ring = { version = "0.16.20", features = ["std"] }
ssh-key = { version = "0.6.1", features = ["rsa", "ed25519"] }
ssh-cipher = { version = "0.2.0", features = [
    "std",
    "chacha20poly1305",
    "aes-cbc",
    "aes-ctr",
    "aes-gcm",
    "tdes",
] }
ssh-packet = { version = "0.1.12", features = [
    "futures",
], path = "../ssh-packet" }

rand = "0.8.5"
digest = "0.10.7"
signature = "2.1.0"
hmac = "0.12.1"

sha1 = "0.10.6"
sha2 = "0.10.8"

[dev-dependencies]
rstest = "0.18.2"
async-std = { version = "1.12.0", features = ["attributes", "unstable"] }

test-log = { version = "0.2.12", default-features = false, features = [
    "trace",
] }
tracing-subscriber = { version = "0.3", default-features = false, features = [
    "env-filter",
    "fmt",
    "tracing-log",
] }

rand = { version = "0.8.5", default-features = false, features = [
    "std",
    "std_rng",
] }

async-trait = "0.1.73"
tokio = { version = "*", features = ["full"] }
tokio-util = { version = "0.7.9", features = ["compat"] }
russh = { path = "../russh/russh" }
russh-keys = { path = "../russh/russh-keys" }
